services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build: 
      context: . # localização do dockerfile
      dockerfile: Dockerfile # nome do arquivo onde está a imagem
      target: production # a imagem a ser selecionada
    working_dir: /app
    ports:
      - 8080:8080
    depends_on:
      - postgres
