name: "Construção do artefato"

on:
  push:
    branches: ["main", "build"]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker login
      uses: docker/login-action@v3
      with:
        username: joao00
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
          push: true
          tags: joao00/go_lang_cicd:latest,joao00/go_lang_cicd:${{ github.sha }}
